library("pastecs")
library("vegan")
library("ggplot2")
library("reshape2")
library("pvclust")
library("stringr")
library("openxlsx")
library(sf)
library(tidyverse)
setwd(here::here())
setwd("./outputs")

KC_scores<-read.csv("B-IBI_results_03082023_2002-2021_NoUnique_subsamp_450_LR_exclude.csv")
KC_scores<-subset(KC_scores, Tot_Abund>=450)

KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")
KC_trends<-subset(KC_trends, !(Site.Code=="09DUW0277"&Stream.or.River=="Riverton Creek (003D)"))
KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
KC_scores<-subset(KC_scores, Site.Code %in% KC_trends$Site.Code)
data<-KC_scores

add_envdata<-read.csv("ENV_data_2022_03062023.csv")
add_envdata$Year<-as.numeric(paste0(add_envdata$Year))



# data$Year<-format(as.Date(data$Visit.Date, '%Y-%m-%d'), "%Y")
envdata<-left_join( data, add_envdata, by=c("Site.Code"="SiteName", "Year"="Year"))
# envdata<-envdata[!str_detect(envdata$Sample.Code, "_R"),]
# envdata<-envdata[!str_detect(envdata$Sample.Code, "[0-9]R[0-9]"),]
# envdata<-envdata[!str_detect(envdata$Sample.Code, "[0-9]R$"),]
# envdata<-envdata[!str_detect(envdata$Sample.Code, "QC"),]
# envdata<-envdata[!str_detect(envdata$Sample.Code, "_r"),]
# envdata<-envdata[!str_detect(envdata$Sample.Code, "Duplicate"),]
means<-ddply(envdata, .(Site.Code), summarize, meanScore=mean(Overall.Score), meanRBForest=mean(per_Forest_RB, na.rm=T), meanRBShrub=mean(per_Scrub.Shrub_RB, na.rm=T), meanBasinUrban=mean(per_Urban_, na.rm=T), meanBasinForest=mean(per_Forest_, na.rm=T))
names(envdata)
ggplot(means, aes(x=meanRBForest, y=meanScore, size=meanBasinUrban))+geom_point()
ggplot(means, aes(x=meanRBForest, y=meanScore, size=meanBasinForest))+geom_point()
ggplot(means, aes(x=meanRBShrub, y=meanScore, size=meanBasinUrban))+geom_point()
ggplot(means, aes(x=meanRBShrub, y=meanScore, size=meanBasinForest))+geom_point()

library(rkt)
l=unique(c(as.character(envdata$Site.Code)))
envdata$Site.Number<-as.numeric(factor(envdata$Site.Code, levels=l))
with(envdata, rkt(date = as.numeric(Year), y = per_Forest_RB, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Forest_x_RB, x=Year, group=Site.Code, color=Site.Code))+geom_line()
ggplot(envdata, aes(x=per_Forest_RB, y=Overall.Score))+geom_point()
cor.test(envdata$Overall.Score, envdata$per_Forest_RB, method="spearman")

library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Forest_RB),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Forest_RB~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Forest_RB),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Forest_RB~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")

data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")
# ggplot(data2_score_trends, aes(y=MKSlope_Overall_Score, x=slope))+geom_point()



with(envdata, rkt(date = as.numeric(Year), y = per_Urban_RB, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Urban_x_RB, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Urban_RB, method="spearman")
ggplot(envdata, aes(x=per_Urban_RB, y=Overall.Score))+geom_point()
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Urban_RB),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Urban_RB~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Urban_RB),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Urban_RB~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = per_Scrub.Shrub_RB, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Scrub.Shrub_x_RB, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Scrub.Shrub_RB, method="spearman")
ggplot(envdata, aes(x=per_Scrub.Shrub_RB, y=Overall.Score))+geom_point()
ggplot(envdata, aes(x=per_Scrub.Shrub_RB+per_Forest_RB, y=Overall.Score))+geom_point()
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Scrub.Shrub_RB),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Scrub.Shrub_RB~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Scrub.Shrub_RB),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Scrub.Shrub_RB~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = per_Open.Spaces.Developed_, block = Site.Number, correct = FALSE, rep="a"))
cor.test(envdata$Overall.Score, envdata$per_Open.Spaces.Developed_, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Open.Spaces.Developed_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Open.Spaces.Developed_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Open.Spaces.Developed_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Open.Spaces.Developed_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = per_Open.Spaces.Developed_RB, block = Site.Number, correct = FALSE, rep="a"))
ggplot(envdata, aes(y=per_Open.Spaces.Developed_RB, x=Year, group=Site.Code, color=Site.Code))+geom_line()
ggplot(envdata, aes(x=per_Open.Spaces.Developed_RB, y=Overall.Score))+geom_point()
ggplot(envdata, aes(x=per_Scrub.Shrub_RB, y=Overall.Score))+geom_point()
cor.test(envdata$Overall.Score, envdata$per_Open.Spaces.Developed_RB, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Open.Spaces.Developed_RB),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Open.Spaces.Developed_RB~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Open.Spaces.Developed_RB),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Open.Spaces.Developed_RB~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")
ggplot(data2_score_trends, aes(y=MKSlope_Overall.Score, x=mk.slope))+geom_point()

# with(envdata, rkt(date = as.numeric(Year), y = per_Unconsolidated.Shore_x, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Unconsolidated.Shore_x, x=Year, group=STAID, color=STAID))+geom_line()


with(envdata, rkt(date = as.numeric(Year), y = WettedWidth, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=WettedWidth, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$WettedWidth, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$WettedWidth),],.(Site.Code),mutate, mk.tau=kendallTrendTest( WettedWidth~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$WettedWidth),],.(Site.Code),mutate, mk.slope=kendallTrendTest( WettedWidth~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")
ggplot(data2_score_trends, aes(x=MKSlope_Overall.Score, y=mk.slope))+geom_point()

with(envdata, rkt(date = as.numeric(Year), y = per_Agricultural_RB, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Agricultural_x_RB, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Agricultural_RB, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Agricultural_RB),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Agricultural_RB~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Agricultural_RB),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Agricultural_RB~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = speed, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=speed, x=Year, group=Site.Code, color=Site.Code))+geom_line()
cor.test(envdata$Overall.Score, envdata$speed, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$speed),],.(Site.Code),mutate, mk.tau=kendallTrendTest( speed~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$speed),],.(Site.Code),mutate, mk.slope=kendallTrendTest( speed~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")
ggplot(data2_score_trends, aes(x=mk.slope, y=MKSlope_Overall.Score))+geom_point()

with(envdata, rkt(date = as.numeric(Year), y = per_Scrub.Shrub_, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Scrub.Shrub_x_RB, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Scrub.Shrub_, method="spearman")
ggplot(envdata, aes(x=per_Scrub.Shrub_, y=Overall.Score))+geom_point()
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Scrub.Shrub_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Scrub.Shrub_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Scrub.Shrub_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Scrub.Shrub_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")
ggplot(data2_score_trends, aes(x=mk.slope, y=MKSlope_Overall.Score))+geom_point()

# with(envdata, rkt(date = as.numeric(Year), y = D50, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=D50, x=Year, group=STAID, color=STAID))+geom_line()
# ggplot(envdata, aes(y=D50, x=Year, group=Year))+geom_boxplot()
# cor.test(envdata$Overall.Score, envdata$D50)
# library(EnvStats)
# data2<- ddply(envdata[!is.na(envdata$D50),], .(STAID), mutate, slope =lm(D50 ~ as.numeric(Year))[[1]][2])
# data2<-ddply(data2,.(STAID),mutate, mk.tau=kendallTrendTest( D50~ as.numeric(Year))$estimate[1])
# data2_trends<-unique(subset(data2, select=c(STAID, slope, mk.tau))) 
# KC_trends<-read.csv("W:/STS/GreenWQA/Biota/BenthosProjects_KC/trends analysis/Data_for_Trends_FWS_manuscript/CSV/B-IBI_sites_w_trends.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall_Score, MKSlope_Overall_Score, Site_Code))
# data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site_Code", by.y="STAID")
# cor.test(data2_score_trends$MKtau_Overall_Score, data2_score_trends$mk.tau)
# cor.test(data2_score_trends$MKSlope_Overall_Score, data2_score_trends$slope)
# ggplot(data2_score_trends, aes(y=MKSlope_Overall_Score, x=slope))+geom_point()

with(envdata, rkt(date = as.numeric(Year), y = RiffleDepth, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=RiffleDepth, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$RiffleDepth, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$RiffleDepth),],.(Site.Code),mutate, mk.tau=kendallTrendTest( RiffleDepth~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$RiffleDepth),],.(Site.Code),mutate, mk.slope=kendallTrendTest( RiffleDepth~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

# with(envdata, rkt(date = as.numeric(Year), y = per_Bare.Land_x_RB, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Bare.Land_x, x=Year, group=STAID, color=STAID))+geom_line()


with(envdata, rkt(date = as.numeric(Year), y = per_Forest_, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Forest_x, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Forest_, method="spearman")
ggplot(envdata, aes(x=per_Forest_x, y=Overall.Score))+geom_point()
ggplot(envdata, aes(x=per_Forest_x+per_Scrub.Shrub_x, y=Overall.Score))+geom_point()
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Forest_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Forest_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Forest_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Forest_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = per_Urban_, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Urban_x, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Urban_, method="spearman")
ggplot(envdata, aes(x=per_Urban_, y=Overall.Score))+geom_point()
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Urban_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Urban_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Urban_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Urban_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = per_Agricultural_, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=per_Agricultural_x, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$per_Agricultural_, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$per_Agricultural_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( per_Agricultural_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$per_Agricultural_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( per_Agricultural_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = PctDev_Basins_, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=Impervious.Cover, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$PctDev_Basins_, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$PctDev_Basins_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( PctDev_Basins_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$PctDev_Basins_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( PctDev_Basins_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

with(envdata, rkt(date = as.numeric(Year), y = PctDev_buffers_, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=Impervious.Cover, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$PctDev_buffers_, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$PctDev_buffers_),],.(Site.Code),mutate, mk.tau=kendallTrendTest( PctDev_buffers_~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$PctDev_buffers_),],.(Site.Code),mutate, mk.slope=kendallTrendTest( PctDev_buffers_~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

# with(envdata, rkt(date = as.numeric(Year), y = DD, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=DD, x=Year, group=STAID, color=STAID))+geom_line()
# cor.test(envdata$Overall.Score, envdata$DD)
# library(EnvStats)
# data2<- ddply(envdata[!is.na(envdata$DD),], .(STAID), mutate, slope =lm(DD ~ as.numeric(Year))[[1]][2])
# data2<-ddply(data2,.(STAID),mutate, mk.tau=kendallTrendTest( DD~ as.numeric(Year))$estimate[1])
# data2_trends<-unique(subset(data2, select=c(STAID, slope, mk.tau))) 
# KC_trends<-read.csv("W:/STS/GreenWQA/Biota/BenthosProjects_KC/trends analysis/Data_for_Trends_FWS_manuscript/CSV/B-IBI_sites_w_trends.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall_Score, MKSlope_Overall_Score, Site_Code))
# data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site_Code", by.y="STAID")
# cor.test(data2_score_trends$MKtau_Overall_Score, data2_score_trends$mk.tau)
# cor.test(data2_score_trends$MKSlope_Overall_Score, data2_score_trends$slope)
# ggplot(data2_score_trends, aes(y=MKSlope_Overall_Score, x=slope))+geom_point()

with(envdata, rkt(date = as.numeric(Year), y = BankfulWidth, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=BankfulWidth, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$BankfulWidth, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$BankfulWidth),],.(Site.Code),mutate, mk.tau=kendallTrendTest( BankfulWidth~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$BankfulWidth),],.(Site.Code),mutate, mk.slope=kendallTrendTest( BankfulWidth~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")

subset(envdata, Site.Code=="09NEW2151"&Year=="2007")
envdata<-subset(envdata, Site.Code!="09NEW2151"&Year!="2007")
with(envdata, rkt(date = as.numeric(Year), y = WettedWidth, block = Site.Number, correct = FALSE, rep="a"))
# ggplot(envdata, aes(y=WettedWidth, x=Year, group=STAID, color=STAID))+geom_line()
cor.test(envdata$Overall.Score, envdata$WettedWidth, method="spearman")
library(EnvStats)
data2<-ddply(envdata[!is.na(envdata$WettedWidth),],.(Site.Code),mutate, mk.tau=kendallTrendTest( WettedWidth~ as.numeric(Year))$estimate[1])
data2<-ddply(data2[!is.na(data2$WettedWidth),],.(Site.Code),mutate, mk.slope=kendallTrendTest( WettedWidth~ as.numeric(Year))$estimate[2])
data2_trends<-unique(subset(data2, select=c(Site.Code, mk.slope, mk.tau))) 
# KC_trends<-read.csv("Site_Trends_coarse_LR_01182023_2002-2021.csv")
# KC_trends<-subset(KC_trends, select=c(MKtau_Overall.Score, MKSlope_Overall.Score, Site.Code, slope_Overall.Score))
data2_score_trends<-merge(KC_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")
summary(data2_score_trends$mk.slope)
# cor.test(data2_score_trends$MKtau_Overall.Score, data2_score_trends$mk.tau)
cor.test(data2_score_trends$MKSlope_Overall.Score, data2_score_trends$mk.slope, method="spearman")
ggplot(data2_score_trends, aes(x=mk.slope, y=MKSlope_Overall.Score))+geom_point()


data2_score_trends<-merge(data2_score_trends, data2_trends,  by.x="Site.Code", by.y="Site.Code")

ggplot(data2_score_trends, aes(x=mk.slope.x, y=MKSlope_Overall.Score, color=mk.slope))+geom_point()

ggplot(data2_score_trends, aes(x=mk.slope.x, y=mk.slope.y, color=mk.slope))+geom_point()

ggplot(data2_score_trends, aes(x=mk.slope_WW, y=MKSlope_Overall.Score, color=mk.tau_RD))+geom_point()
names(data2_score_trends)[5]<-"mk.slope_WW"
names(data2_score_trends)[7]<-"mk.slope_BF"
names(data2_score_trends)[9]<-"mk.slope_RD"
names(data2_score_trends)[11]<-"mk.slope_Vel"

names(data2_score_trends)[6]<-"mk.tau_WW"
names(data2_score_trends)[8]<-"mk.tau_BF"
names(data2_score_trends)[10]<-"mk.tau_RD"
names(data2_score_trends)[12]<-"mk.tau_Vel"
# LU<-read.csv("LandUse.csv")
# Bibi<-read.csv("CSV/B-IBI_sites_w_trends.csv")
# Bibi<-subset(Bibi, MKtau_Overall_Score>0)
# # LU_trending<-LU[which(LU$Name %in% Bibi$Site_Code),]
# LU$trend<-""
# LU[which(LU$Name %in% Bibi$Site_Code),]$trend<-"TRUE"
# ggplot(LU, aes(y=acres, x=trend,group=trend))+geom_boxplot()
# envdata<-envdata[which(envdata$STAID %in% Bibi$Site_Code),]

KC_trends<-read.csv("Site_Trends_coarse_LR_03092023_2002-2021_LRexclude.csv")
KC_trends<-subset(KC_trends, !(Site.Code=="09DUW0277"&Stream.or.River=="Riverton Creek (003D)"))

posenv<-merge(envdata, KC_trends[, c("Site.Code", "MKtrend_Overall.Score")])

ggplot(posenv, aes(y=Acres, x=MKtrend_Overall.Score,group=MKtrend_Overall.Score))+geom_boxplot()
